server:
  address: 0.0.0.0
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/my_playlist?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MARIA_DB_USER}
    password: ${MARIA_DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  data:
    redis:
      host: localhost
      port: 6379
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      chain:
        cache: false
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/


myPlaylist:
  remember.me.key: ${REMEMBER_ME_KEY:topsecret}

nextcloud:
  webdav-url: ${NEXTCLOUD_WEBDAV_URL}
  username: ${USERNAME_NEXTCLOUD}
  password: ${NEXT_CLOUD_PASSWORD}
  share-link: ${NEXT_CLOUD_SHARE_LINK}

mail:
  myPlaylist: "myplaylist@mail.org"
  host: localhost
  port: 1025
  username: ${MAIL_USER:myPlaylist}
  password: ${MAIL_PASSWORD:topsecret}


logging:
  level:
#    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
#    org.springframework.security: TRACE
